GET http://localhost:3001/

# GET http://localhost:3001/
# test_server for inventory management system API 

# HTTP/1.1 200 OK
# X-Powered-By: Express
# Access-Control-Allow-Origin: *
# Content-Type: application/json; charset=utf-8
# Content-Length: 60
# ETag: W/"3c-LEAFLA3tEJEhxG1O2L3DHG513n4"
# Date: Thu, 14 May 2026 13:10:17 GMT
# Connection: close

# {
#   "message": "Welcome to the inventory management system API"
# }


